### ISSUE TITLE
(TrackModel) Foolproof train movement between blocks

### ISSUE THREAD

**Issue by xaviertorgerson** [xaviertorgerson/North-Shore-Extension#12]
Ensure proper units of speed and authority are sent to Train.  Currently train displacement is monitored in feet but block length in meters causing the train to move to the next block before the end.  Additionally the next block it goes to may be wrong if it is neighboring a switch that has just flipped.

**Comment by xaviertorgerson** [comment]
What units is the authority passed to me from the CTC office? 
What are the desired units for authority to be passed into the Train?

**Comment by saworms** [comment]
Send it in to the train as miles and I will send back the displacement in feet

**Comment by Riteshlogin** [comment]
Okay, does that mean I'm sending it in as miles? I can definitely do that. 

Also, don't know whether this has to do with me or not, but right now the train's position is being printed in feet but it looks like meters. (i.e. block 84 is 300 meters long but it'll print out at 298ft on block 84)

EDIT: After a little bit of testing, I am now very convinced that this unit disparity is causing the displayed authority on the train model GUI to be very different from its actual authority. For now I am taking meters from the track model and multiplying that by 0.00062 (or something like that) to get miles, and then subtracting as the train moves along.

**Comment by saworms** [comment]
Units are changed to be proper values
