### ISSUE TITLE
(TrackModel + TrackController) Go parameter

### ISSUE THREAD

**Issue by xaviertorgerson** [xaviertorgerson/North-Shore-Extension#13]
Only send new speed an authority settings to a train if (GO) parameter is set.

**Comment by xaviertorgerson** [comment]
Should the default be 0 or 1?

**Comment by jtd45** [comment]
just leave it as 0(STOP), it makes everything much safer, especially if the PLC code isn't set up right

**Comment by jtd45** [comment]
Go still doesn't do anything, when it's false it should give the train 0 authority to stop it

**Comment by xaviertorgerson** [comment]
Sorry about that when it was false it just wasn't updating the speed and authority.  I changed it in my latest build
