### ISSUE TITLE
(CTC Office) - Not All Destinations Reachable

### ISSUE THREAD

**Issue by jtd45** [xaviertorgerson/North-Shore-Extension#15]
In Build_5 of the system the CTC Office can not dispatch a train to green line block # 1 or any block not in a continuous path from the yard

**Comment by Riteshlogin** [comment]
This is partially due to the infinite loop in the track model, but when I talked to Xavier today he said he was pretty sure he knew how to fix it (I think)

**Comment by xaviertorgerson** [comment]
Fixed the loop, all destinations on the green line now work
