### ISSUE TITLE
(Train Model + Track Model) Unit discrepancy somewhere between the CTC and the train model

### ISSUE THREAD

**Issue by Riteshlogin** [xaviertorgerson/North-Shore-Extension#19]
If you try sending the train from the green yard to block 96, (which is about 5100 meters, or 3.something miles, the beginning authority displayed on the train model is indeed 3.something miles, but it very quickly goes to negative miles.

**Comment by saworms** [comment]
The train model does not change the authority at any place and just displays the authority it was given in.  It is probably somewhere in the Track Model (maybe he reads it as feet, but it should be read as miles)

**Comment by saworms** [comment]
Issue was that the update function was being called more than expected
