### ISSUE TITLE
(CTC Office + Wayside Controller) TrainOccupancyUpdate called too often

### ISSUE THREAD

**Issue by Riteshlogin** [xaviertorgerson/North-Shore-Extension#20]
Unless it was meant to happen, which is a possibility, the wayside controller calls the trainOccupancyUpdate function much too often, unless this is on purpose

EDIT: Have accounted for this, no longer a problem

**Comment by jtd45** [comment]
It's on purpose, It should call that every track update, I'm not really tracking if the train has moved, I could add that if it is necessary however
