### ISSUE TITLE
(Train Controller) - PID needs better Kp Ki values

### ISSUE THREAD

**Issue by saworms** [xaviertorgerson/North-Shore-Extension#6]
Need to get better values for Kp and Ki to make train power smoother

**Comment by xaviertorgerson** [comment]
http://robotics.stackexchange.com/questions/167/what-are-good-strategies-for-tuning-pid-loops

I found this source useful when tuning the PID controller on micromouse

**Comment by saworms** [comment]
Found PID constants that preform ideally
